### ISSUE TITLE
Deprecation of PHP for project websites

### ISSUE THREAD

**Issue by ptziegler** [eclipse-windowbuilder/windowbuilder-website#10]
See https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1934

**Comment by ptziegler** [comment]
After reading through the issue a bit, I think the intended approach is to use [Hugo](https://gitlab.eclipse.org/eclipsefdn/it/webdev/hugo-eclipsefdn-website-boilerplate#how-to-build-my-projects-website-with-jenkins) to create a static HTML page.

The Hugo sources should be stored in a separate repository which we'd have to request from the Helpdesk team.

**Comment by merks** [comment]
You can create a repository by editing this file and creating a pull request 

https://github.com/eclipse-windowbuilder/.eclipsefdn/blob/main/otterdog/eclipse-windowbuilder.jsonnet

**Comment by ptziegler** [comment]
...I totally forgot about OtterDog. Thank's for the heads-up 😅

**Comment by ptziegler** [comment]
Migration done as part of https://github.com/eclipse-windowbuilder/windowbuilder-website-source/pull/1

> Note that each and every Eclipse project automatically gets a Git repository with git.eclipse.org/www.eclipse.org/<project_name> (see this [repository index](https://git.eclipse.org/r/plugins/gitiles/www.eclipse.org/) for complete list). This is not where you want to push your Hugo sources. This repository contains the webpages that are automatically and regularly pulled and published on the [www.eclipse.org](http://www.eclipse.org/) HTTP server.

I assume that `git.eclipse.org/www.eclipse.org/<project_name>` means _this_ repository, given that that's what's set in the repository index.

And if I understand the readme correctly, the Hugo sources should *not* be hosted here but rather over at [windowbuilder-website-source](https://github.com/eclipse-windowbuilder/windowbuilder-website-source).

What's still not clear to me is how the Jenkins job knows that this repository exists...

**Comment by ptziegler** [comment]
Migration is effectively done, once the pull request is merged:
https://github.com/eclipse-windowbuilder/windowbuilder-website-source/pull/2

The generated files can already be seen here:
https://github.com/eclipse-windowbuilder/windowbuilder-website/tree/staging

Preview:
![image](https://github.com/eclipse-windowbuilder/windowbuilder-website/assets/70652978/3a8dc232-a9c4-42d7-aad6-2847e674fa9e)
![image](https://github.com/eclipse-windowbuilder/windowbuilder-website/assets/70652978/5875a04b-0f6e-42df-8c79-e3e698d26923)

I don't believe the Jenkinsfile from the hugo template project works very well with a multi-branch Jenkins project. I'll have to think about how this can be improved to find a better way to build the website also for PRs.

**Comment by ptziegler** [comment]
Some minor cleanup is still required but the general functionality is there.
